// Stat glossary — definitions for hover tooltips. Source: row 25 of the standard stat CSV.
export const GLOSSARY: Record<string, string> = {
  // Identity
  Number: "Jersey number",
  Last: "Last name",
  First: "First name",
  GP: "Games played",
  // Batting
  PA: "Plate appearances",
  AB: "At bats",
  AVG: "Batting average (H/AB)",
  OBP: "On-base percentage",
  OPS: "On-base plus slugging",
  SLG: "Slugging percentage",
  H: "Hits",
  "1B": "Singles",
  "2B": "Doubles",
  "3B": "Triples",
  HR: "Home runs",
  RBI: "Runs batted in",
  R: "Runs scored",
  BB: "Walks (bases on balls)",
  SO: "Strikeouts",
  "K-L": "Strikeouts looking",
  HBP: "Hit by pitch",
  SAC: "Sacrifice bunts",
  SF: "Sacrifice flies",
  ROE: "Reached on error",
  FC: "Fielder's choice",
  SB: "Stolen bases",
  "SB%": "Stolen base percentage",
  CS: "Caught stealing",
  PIK: "Picked off",
  QAB: "Quality at bats",
  "QAB%": "Quality at bat percentage",
  "PA/BB": "Plate appearances per walk",
  "BB/K": "Walk to strikeout ratio",
  "C%": "Contact percentage",
  HHB: "Hard-hit balls",
  "LD%": "Line drive percentage",
  "FB%": "Fly ball percentage",
  "GB%": "Ground ball percentage",
  BABIP: "Batting average on balls in play",
  "BA/RISP": "Batting average with runners in scoring position",
  LOB: "Runners left on base",
  "2OUTRBI": "Two-out RBIs",
  XBH: "Extra-base hits",
  TB: "Total bases",
  PS: "Pitches seen",
  "PS/PA": "Pitches seen per plate appearance",
  "2S+3": "At bats reaching 2 strikes plus 3 balls",
  "2S+3%": "Percentage of ABs reaching 2S+3",
  "6+": "At bats of 6+ pitches",
  "6+%": "Percentage of ABs going 6+ pitches",
  "AB/HR": "At bats per home run",
  GIDP: "Grounded into double play",
  GITP: "Grounded into triple play",
  CI: "Catcher's interference",
  // Pitching
  IP: "Innings pitched",
  GS: "Games started",
  BF: "Batters faced",
  "#P": "Total pitches thrown",
  W: "Wins",
  L: "Losses",
  SV: "Saves",
  SVO: "Save opportunities",
  BS: "Blown saves",
  "SV%": "Save percentage",
  ER: "Earned runs",
  ERA: "Earned run average",
  WHIP: "Walks + hits per inning pitched",
  BK: "Balks",
  WP: "Wild pitches",
  BAA: "Batting average against",
  "P/IP": "Pitches per inning",
  "P/BF": "Pitches per batter faced",
  "<3%": "Percentage of innings pitched in under 3 pitches",
  LOO: "Lead-off outs",
  "1ST2OUT": "First two batters out",
  "123INN": "1-2-3 innings",
  "<13": "Pitches in under 13",
  FIP: "Fielding independent pitching",
  "S%": "Strike percentage",
  "FPS%": "First pitch strike percentage",
  "FPSO%": "First pitch strike → out percentage",
  "FPSW%": "First pitch strike → walk percentage",
  "FPSH%": "First pitch strike → hit percentage",
  "BB/INN": "Walks per inning",
  "0BBINN": "Walk-free innings",
  BBS: "Walks scored",
  LOBB: "Lead-off walks",
  LOBBS: "Lead-off walks scored",
  "SM%": "Swing and miss percentage",
  "K/BF": "Strikeouts per batter faced",
  "K/BB": "Strikeout to walk ratio",
  "WEAK%": "Weak contact percentage",
  "HHB%": "Hard-hit ball percentage allowed",
  "GO/AO": "Ground out to air out ratio",
  TopMPH: "Top pitch velocity",
  FB: "Fastballs",
  FBS: "Fastball strikes",
  "FBS%": "Fastball strike percentage",
  "FBSW%": "Fastball swing percentage",
  "FBSM%": "Fastball swing-and-miss percentage",
  MPHFB: "Average fastball velocity",
  TopFB: "Top fastball velocity",
  CB: "Curveballs",
  CBS: "Curveball strikes",
  "CBS%": "Curveball strike percentage",
  "CBSW%": "Curveball swing percentage",
  "CBSM%": "Curveball swing-and-miss percentage",
  MPHCB: "Average curveball velocity",
  TopCB: "Top curveball velocity",
  CT: "Cutters",
  CTS: "Cutter strikes",
  "CTS%": "Cutter strike percentage",
  "CTSW%": "Cutter swing percentage",
  "CTSM%": "Cutter swing-and-miss percentage",
  MPHCT: "Average cutter velocity",
  TopCT: "Top cutter velocity",
  SL: "Sliders",
  SLS: "Slider strikes",
  "SLS%": "Slider strike percentage",
  "SLSW%": "Slider swing percentage",
  "SLSM%": "Slider swing-and-miss percentage",
  MPHSL: "Average slider velocity",
  TopSL: "Top slider velocity",
  CH: "Changeups",
  CHS: "Changeup strikes",
  "CHS%": "Changeup strike percentage",
  "CHSW%": "Changeup swing percentage",
  "CHSM%": "Changeup swing-and-miss percentage",
  MPHCH: "Average changeup velocity",
  TopCH: "Top changeup velocity",
  OS: "Other pitches",
  OSS: "Other pitch strikes",
  "OSS%": "Other pitch strike percentage",
  "OSSW%": "Other pitch swing percentage",
  "OSSM%": "Other pitch swing-and-miss percentage",
  MPHOS: "Average other pitch velocity",
  TopOS: "Top other pitch velocity",
  // Fielding
  TC: "Total chances",
  A: "Assists",
  PO: "Putouts",
  FPCT: "Fielding percentage",
  E: "Errors",
  DP: "Double plays",
  TP: "Triple plays",
  INN: "Innings played in field",
  PB: "Passed balls",
  SBATT: "Stolen base attempts against",
  "CS%": "Caught stealing percentage",
  P: "Pitcher",
  C: "Catcher",
  LF: "Left field",
  CF: "Center field",
  RF: "Right field",
  Total: "Total fielding chances all positions",
};

// Key stats shown by default on player pages
export const KEY_BATTING = ["GP", "PA", "AB", "AVG", "OBP", "SLG", "OPS", "H", "HR", "RBI", "R", "BB", "SO", "SB"];
export const KEY_PITCHING = ["IP", "W", "L", "SV", "ERA", "WHIP", "SO", "BB", "H", "BAA", "K/BB", "BF"];
export const KEY_FIELDING = ["TC", "PO", "A", "E", "FPCT", "DP"];

// Column ranges per user spec (1-indexed letters from CSV)
// D-BB = batting (cols 4..54), BC-EY = pitching (cols 55..155), EZ-FY = fielding (cols 156..181)
export const BATTING_RANGE: [number, number] = [3, 53];   // 0-indexed inclusive
export const PITCHING_RANGE: [number, number] = [54, 154];
export const FIELDING_RANGE: [number, number] = [155, 180];
