// Generated by `supabase gen types typescript` (regenerated 2026-05-10).
// Helper unions at the top are hand-maintained and preserve strict
// types for callers that pre-existed the generator.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ---- Hand-maintained domain unions (kept across regenerations) -------------

export type Sport = "baseball" | "softball";
export type TeamLevel = "varsity" | "jv" | "freshman" | "middle_school";
export type SchoolRole = "owner" | "admin";
export type TeamRole = "coach" | "scorer" | "assistant";
export type GameLocation = "home" | "away" | "neutral";
export type GameResult = "W" | "L" | "T";
export type GameStatus = "draft" | "in_progress" | "final";
export type GameResultType = "regulation" | "shortened" | "forfeit" | "suspended";
export type InningHalf = "top" | "bottom";

export type GameEventType =
  | "at_bat"
  | "stolen_base"
  | "caught_stealing"
  | "pickoff"
  | "wild_pitch"
  | "passed_ball"
  | "balk"
  | "error_advance"
  | "substitution"
  | "pitching_change"
  | "position_change"
  | "game_started"
  | "inning_end"
  | "game_finalized"
  | "correction"
  | "pitch"
  | "defensive_conference"
  | "opposing_lineup_edit";

// ---- Generated Database type (regenerated; do not hand-edit) ----------------

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      at_bats: {
        Row: {
          balls: number;
          batter_id: string | null;
          batting_order: number | null;
          created_at: string;
          description: string | null;
          event_id: string;
          fielder_position: string | null;
          game_id: string;
          half: string;
          id: string;
          inning: number;
          opponent_batter_id: string | null;
          opponent_pitcher_id: string | null;
          outs_recorded: number;
          pitch_count: number;
          pitcher_id: string | null;
          rbi: number;
          result: string;
          runs_scored_on_play: number;
          spray_x: number | null;
          spray_y: number | null;
          strikes: number;
        };
        Insert: {
          balls?: number;
          batter_id?: string | null;
          batting_order?: number | null;
          created_at?: string;
          description?: string | null;
          event_id: string;
          fielder_position?: string | null;
          game_id: string;
          half: string;
          id?: string;
          inning: number;
          opponent_batter_id?: string | null;
          opponent_pitcher_id?: string | null;
          outs_recorded?: number;
          pitch_count?: number;
          pitcher_id?: string | null;
          rbi?: number;
          result: string;
          runs_scored_on_play?: number;
          spray_x?: number | null;
          spray_y?: number | null;
          strikes?: number;
        };
        Update: Partial<Database["public"]["Tables"]["at_bats"]["Insert"]>;
        Relationships: [];
      };
      opponent_players: {
        Row: {
          bats: string | null;
          created_at: string;
          external_player_id: string | null;
          first_name: string | null;
          grad_year: number | null;
          id: string;
          jersey_number: string | null;
          last_name: string | null;
          opponent_team_id: string | null;
          school_id: string;
          throws: string | null;
          updated_at: string;
        };
        Insert: {
          bats?: string | null;
          created_at?: string;
          external_player_id?: string | null;
          first_name?: string | null;
          grad_year?: number | null;
          id?: string;
          jersey_number?: string | null;
          last_name?: string | null;
          opponent_team_id?: string | null;
          school_id: string;
          throws?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["opponent_players"]["Insert"]>;
        Relationships: [];
      };
      csv_uploads: {
        Row: {
          created_at: string;
          filename: string | null;
          id: string;
          notes: string | null;
          player_count: number;
          season_year: number | null;
          team_id: string;
          upload_date: string;
        };
        Insert: {
          created_at?: string;
          filename?: string | null;
          id?: string;
          notes?: string | null;
          player_count?: number;
          season_year?: number | null;
          team_id: string;
          upload_date: string;
        };
        Update: Partial<Database["public"]["Tables"]["csv_uploads"]["Insert"]>;
        Relationships: [];
      };
      game_events: {
        Row: {
          client_event_id: string;
          created_at: string;
          created_by: string | null;
          event_type: GameEventType;
          game_id: string;
          id: string;
          payload: Json;
          sequence_number: number;
          supersedes_event_id: string | null;
        };
        // sequence_number is filled by the assign_game_event_sequence
        // BEFORE INSERT trigger; clients omit it.
        Insert: {
          client_event_id: string;
          created_at?: string;
          created_by?: string | null;
          event_type: GameEventType;
          game_id: string;
          id?: string;
          payload: Json;
          sequence_number?: number;
          supersedes_event_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["game_events"]["Insert"]>;
        Relationships: [];
      };
      game_links: {
        Row: {
          confirmed_at: string;
          confirmed_by: string | null;
          home_game_id: string;
          id: string;
          visitor_game_id: string;
        };
        Insert: {
          confirmed_at?: string;
          confirmed_by?: string | null;
          home_game_id: string;
          id?: string;
          visitor_game_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["game_links"]["Insert"]>;
        Relationships: [];
      };
      game_live_state: {
        Row: {
          game_id: string;
          half: InningHalf;
          inning: number;
          last_event_at: string | null;
          last_play_text: string | null;
          opponent_score: number;
          outs: number;
          runner_first: string | null;
          runner_second: string | null;
          runner_third: string | null;
          team_score: number;
          updated_at: string;
        };
        Insert: {
          game_id: string;
          half?: InningHalf;
          inning?: number;
          last_event_at?: string | null;
          last_play_text?: string | null;
          opponent_score?: number;
          outs?: number;
          runner_first?: string | null;
          runner_second?: string | null;
          runner_third?: string | null;
          team_score?: number;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["game_live_state"]["Insert"]>;
        Relationships: [];
      };
      game_opponent_pitchers: {
        Row: {
          created_at: string;
          game_id: string;
          id: string;
          name: string;
          opponent_player_id: string | null;
        };
        Insert: {
          created_at?: string;
          game_id: string;
          id?: string;
          name: string;
          opponent_player_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["game_opponent_pitchers"]["Insert"]>;
        Relationships: [];
      };
      games: {
        Row: {
          created_at: string;
          finalized_at: string | null;
          game_date: string;
          game_sequence: number;
          game_time: string | null;
          id: string;
          is_final: boolean;
          is_home: boolean;
          location: GameLocation;
          notes: string | null;
          opponent: string;
          opponent_score: number | null;
          opponent_team_id: string | null;
          result: GameResult | null;
          result_type: GameResultType;
          season_year: number | null;
          status: GameStatus;
          team_id: string;
          team_score: number | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          finalized_at?: string | null;
          game_date: string;
          game_sequence?: number;
          game_time?: string | null;
          id?: string;
          is_final?: boolean;
          is_home: boolean;
          location?: GameLocation;
          notes?: string | null;
          opponent: string;
          opponent_score?: number | null;
          opponent_team_id?: string | null;
          result?: GameResult | null;
          result_type?: GameResultType;
          season_year?: number | null;
          status?: GameStatus;
          team_id: string;
          team_score?: number | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["games"]["Insert"]>;
        Relationships: [];
      };
      players: {
        Row: {
          created_at: string;
          first_name: string;
          grad_year: number | null;
          id: string;
          last_name: string;
          school_id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          first_name: string;
          grad_year?: number | null;
          id?: string;
          last_name: string;
          school_id: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["players"]["Insert"]>;
        Relationships: [];
      };
      roster_entries: {
        Row: {
          created_at: string;
          id: string;
          jersey_number: string | null;
          player_id: string;
          position: string | null;
          season_year: number;
          team_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          jersey_number?: string | null;
          player_id: string;
          position?: string | null;
          season_year: number;
          team_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["roster_entries"]["Insert"]>;
        Relationships: [];
      };
      school_admins: {
        Row: {
          allow_coach_contact: boolean;
          created_at: string;
          role: SchoolRole;
          school_id: string;
          user_id: string;
        };
        Insert: {
          allow_coach_contact?: boolean;
          created_at?: string;
          role?: SchoolRole;
          school_id: string;
          user_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["school_admins"]["Insert"]>;
        Relationships: [];
      };
      schools: {
        Row: {
          association: string | null;
          classification: string | null;
          created_at: string;
          division: string | null;
          id: string;
          is_discoverable: boolean;
          is_public_roster: boolean;
          logo_url: string | null;
          name: string;
          primary_color: string | null;
          public_scores_enabled: boolean;
          secondary_color: string | null;
          short_name: string | null;
          slug: string;
          timezone: string;
          updated_at: string;
        };
        Insert: {
          association?: string | null;
          classification?: string | null;
          created_at?: string;
          division?: string | null;
          id?: string;
          is_discoverable?: boolean;
          is_public_roster?: boolean;
          logo_url?: string | null;
          name: string;
          primary_color?: string | null;
          public_scores_enabled?: boolean;
          secondary_color?: string | null;
          short_name?: string | null;
          slug: string;
          timezone?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["schools"]["Insert"]>;
        Relationships: [];
      };
      score_discrepancies: {
        Row: {
          game_link_id: string;
          home_acct_home_score: number | null;
          home_acct_visitor_score: number | null;
          home_self_confirmed: boolean;
          id: string;
          opened_at: string;
          resolved_at: string | null;
          vis_acct_home_score: number | null;
          vis_acct_visitor_score: number | null;
          visitor_self_confirmed: boolean;
        };
        Insert: {
          game_link_id: string;
          home_acct_home_score?: number | null;
          home_acct_visitor_score?: number | null;
          home_self_confirmed?: boolean;
          id?: string;
          opened_at?: string;
          resolved_at?: string | null;
          vis_acct_home_score?: number | null;
          vis_acct_visitor_score?: number | null;
          visitor_self_confirmed?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["score_discrepancies"]["Insert"]>;
        Relationships: [];
      };
      stat_snapshots: {
        Row: {
          created_at: string;
          game_id: string | null;
          id: string;
          player_id: string;
          season_year: number | null;
          source: "xlsx" | "tablet";
          stats: Json;
          team_id: string;
          upload_date: string;
          upload_id: string | null;
        };
        Insert: {
          created_at?: string;
          game_id?: string | null;
          id?: string;
          player_id: string;
          season_year?: number | null;
          source?: "xlsx" | "tablet";
          stats: Json;
          team_id: string;
          upload_date: string;
          upload_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["stat_snapshots"]["Insert"]>;
        Relationships: [];
      };
      team_members: {
        Row: {
          created_at: string;
          role: TeamRole;
          team_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          role?: TeamRole;
          team_id: string;
          user_id: string;
        };
        Update: Partial<Database["public"]["Tables"]["team_members"]["Insert"]>;
        Relationships: [];
      };
      teams: {
        Row: {
          created_at: string;
          id: string;
          league_type: "mlb" | "nfhs";
          level: TeamLevel;
          name: string;
          nfhs_state: string | null;
          pitch_limits: Json | null;
          school_id: string;
          slug: string;
          sport: Sport;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          league_type?: "mlb" | "nfhs";
          level: TeamLevel;
          name: string;
          nfhs_state?: string | null;
          pitch_limits?: Json | null;
          school_id: string;
          slug: string;
          sport: Sport;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["teams"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      _score_discrepancy_recompute_for_link: {
        Args: { p_link_id: string; p_score_changed_side: string };
        Returns: undefined;
      };
      apply_relink: {
        Args: { p_game_ids: string[]; p_target_team_id: string };
        Returns: number;
      };
      confirm_game_link: {
        Args: { p_home_game_id: string; p_visitor_game_id: string };
        Returns: string;
      };
      confirm_my_score: { Args: { p_link_id: string }; Returns: undefined };
      create_school: {
        Args: { p_name: string; p_slug: string };
        Returns: Database["public"]["Tables"]["schools"]["Row"];
      };
      find_relink_suggestions: {
        Args: { p_team_id: string };
        Returns: {
          candidate_school_id: string;
          candidate_school_name: string;
          candidate_school_short_name: string;
          candidate_team_id: string;
          candidate_team_level: string;
          candidate_team_name: string;
          game_date: string;
          game_id: string;
          game_time: string;
          opponent_text: string;
        }[];
      };
      game_match_candidates: {
        Args: { p_my_game_id: string };
        Returns: {
          candidate_game_id: string;
          game_date: string;
          game_sequence: number;
          game_time: string;
          is_home: boolean;
          status: string;
        }[];
      };
      ingest_schedule: {
        Args: {
          p_games: Json;
          p_on_conflict: string;
          p_school: string;
          p_team: string;
        };
        Returns: {
          conflict_dates: string[];
          inserted: number;
          skipped: number;
          updated: number;
        }[];
      };
      ingest_stats_workbook: {
        Args: {
          p_filename: string;
          p_players: Json;
          p_replace: boolean;
          p_school: string;
          p_team: string;
          p_upload_date: string;
        };
        Returns: { snapshot_count: number; upload_id: string }[];
      };
      get_public_roster: {
        Args: { p_team_id: string; p_season_year: number };
        Returns: {
          external_player_id: string;
          first_name: string | null;
          last_name: string | null;
          jersey_number: string | null;
          position: string | null;
          grad_year: number | null;
        }[];
      };
      upsert_opponent_players: {
        Args: { p_school: string; p_rows: Json };
        Returns: { client_ref: string; opponent_player_id: string }[];
      };
      is_school_admin: { Args: { p_school: string }; Returns: boolean };
      is_season_closed: { Args: { yr: number }; Returns: boolean };
      is_team_member: { Args: { p_team: string }; Returns: boolean };
      season_year_for: { Args: { d: string }; Returns: number };
      unlink_games: { Args: { p_link_id: string }; Returns: undefined };
      upsert_roster: {
        Args: {
          p_has_grad_year: boolean;
          p_has_number: boolean;
          p_has_position: boolean;
          p_players: Json;
          p_school: string;
          p_season: number;
          p_team: string;
        };
        Returns: { first_name: string; last_name: string; player_id: string }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
