// Generated by `supabase gen types typescript` (regenerated 2026-05-11).
// Helper unions at the top are hand-maintained and preserve strict
// types for callers that pre-existed the generator.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ---- Hand-maintained domain unions (kept across regenerations) -------------

export type Sport = "baseball" | "softball";
export type TeamLevel = "varsity" | "jv" | "freshman" | "middle_school";
export type SchoolRole = "owner" | "admin";
export type TeamRole = "coach" | "scorer" | "assistant";
export type GameLocation = "home" | "away" | "neutral";
export type GameResult = "W" | "L" | "T";
export type GameStatus = "draft" | "in_progress" | "final";
export type GameResultType = "regulation" | "shortened" | "forfeit" | "suspended";
export type InningHalf = "top" | "bottom";

export type GameEventType =
  | "at_bat"
  | "stolen_base"
  | "caught_stealing"
  | "pickoff"
  | "wild_pitch"
  | "passed_ball"
  | "balk"
  | "error_advance"
  | "substitution"
  | "pitching_change"
  | "position_change"
  | "game_started"
  | "inning_end"
  | "game_finalized"
  | "correction"
  | "pitch"
  | "defensive_conference"
  | "opposing_lineup_edit";

// ---- Generated Database type (regenerated; do not hand-edit) ----------------

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      at_bats: {
        Row: {
          balls: number
          batter_id: string | null
          batting_order: number | null
          created_at: string
          description: string | null
          event_id: string
          fielder_position: string | null
          game_id: string
          half: string
          id: string
          inning: number
          opponent_batter_id: string | null
          opponent_pitcher_id: string | null
          outs_recorded: number
          pitch_count: number
          pitcher_id: string | null
          rbi: number
          result: string
          runs_scored_on_play: number
          spray_x: number | null
          spray_y: number | null
          strikes: number
        }
        Insert: {
          balls?: number
          batter_id?: string | null
          batting_order?: number | null
          created_at?: string
          description?: string | null
          event_id: string
          fielder_position?: string | null
          game_id: string
          half: string
          id?: string
          inning: number
          opponent_batter_id?: string | null
          opponent_pitcher_id?: string | null
          outs_recorded?: number
          pitch_count?: number
          pitcher_id?: string | null
          rbi?: number
          result: string
          runs_scored_on_play?: number
          spray_x?: number | null
          spray_y?: number | null
          strikes?: number
        }
        Update: {
          balls?: number
          batter_id?: string | null
          batting_order?: number | null
          created_at?: string
          description?: string | null
          event_id?: string
          fielder_position?: string | null
          game_id?: string
          half?: string
          id?: string
          inning?: number
          opponent_batter_id?: string | null
          opponent_pitcher_id?: string | null
          outs_recorded?: number
          pitch_count?: number
          pitcher_id?: string | null
          rbi?: number
          result?: string
          runs_scored_on_play?: number
          spray_x?: number | null
          spray_y?: number | null
          strikes?: number
        }
        Relationships: [
          {
            foreignKeyName: "at_bats_batter_id_fkey"
            columns: ["batter_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "at_bats_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: true
            referencedRelation: "game_events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "at_bats_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "at_bats_opponent_batter_id_fkey"
            columns: ["opponent_batter_id"]
            isOneToOne: false
            referencedRelation: "opponent_players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "at_bats_opponent_pitcher_fk"
            columns: ["opponent_pitcher_id"]
            isOneToOne: false
            referencedRelation: "game_opponent_pitchers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "at_bats_pitcher_id_fkey"
            columns: ["pitcher_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      csv_uploads: {
        Row: {
          created_at: string
          filename: string | null
          id: string
          notes: string | null
          player_count: number
          season_year: number | null
          team_id: string
          upload_date: string
        }
        Insert: {
          created_at?: string
          filename?: string | null
          id?: string
          notes?: string | null
          player_count?: number
          season_year?: number | null
          team_id: string
          upload_date: string
        }
        Update: {
          created_at?: string
          filename?: string | null
          id?: string
          notes?: string | null
          player_count?: number
          season_year?: number | null
          team_id?: string
          upload_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "csv_uploads_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      game_events: {
        Row: {
          client_event_id: string
          created_at: string
          created_by: string | null
          event_type: string
          game_id: string
          id: string
          payload: Json
          sequence_number: number | null
          supersedes_event_id: string | null
        }
        Insert: {
          client_event_id: string
          created_at?: string
          created_by?: string | null
          event_type: string
          game_id: string
          id?: string
          payload: Json
          sequence_number?: number | null
          supersedes_event_id?: string | null
        }
        Update: {
          client_event_id?: string
          created_at?: string
          created_by?: string | null
          event_type?: string
          game_id?: string
          id?: string
          payload?: Json
          sequence_number?: number | null
          supersedes_event_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "game_events_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_events_supersedes_event_id_fkey"
            columns: ["supersedes_event_id"]
            isOneToOne: false
            referencedRelation: "game_events"
            referencedColumns: ["id"]
          },
        ]
      }
      game_links: {
        Row: {
          confirmed_at: string
          confirmed_by: string | null
          home_game_id: string
          id: string
          visitor_game_id: string
        }
        Insert: {
          confirmed_at?: string
          confirmed_by?: string | null
          home_game_id: string
          id?: string
          visitor_game_id: string
        }
        Update: {
          confirmed_at?: string
          confirmed_by?: string | null
          home_game_id?: string
          id?: string
          visitor_game_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_links_home_game_id_fkey"
            columns: ["home_game_id"]
            isOneToOne: true
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_links_visitor_game_id_fkey"
            columns: ["visitor_game_id"]
            isOneToOne: true
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
      game_live_state: {
        Row: {
          game_id: string
          half: string
          inning: number
          last_event_at: string | null
          last_play_text: string | null
          opponent_score: number
          outs: number
          runner_first: string | null
          runner_second: string | null
          runner_third: string | null
          team_score: number
          updated_at: string
        }
        Insert: {
          game_id: string
          half?: string
          inning?: number
          last_event_at?: string | null
          last_play_text?: string | null
          opponent_score?: number
          outs?: number
          runner_first?: string | null
          runner_second?: string | null
          runner_third?: string | null
          team_score?: number
          updated_at?: string
        }
        Update: {
          game_id?: string
          half?: string
          inning?: number
          last_event_at?: string | null
          last_play_text?: string | null
          opponent_score?: number
          outs?: number
          runner_first?: string | null
          runner_second?: string | null
          runner_third?: string | null
          team_score?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_live_state_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: true
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_live_state_runner_first_fkey"
            columns: ["runner_first"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_live_state_runner_second_fkey"
            columns: ["runner_second"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_live_state_runner_third_fkey"
            columns: ["runner_third"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      game_opponent_pitchers: {
        Row: {
          created_at: string
          game_id: string
          id: string
          name: string
          opponent_player_id: string | null
        }
        Insert: {
          created_at?: string
          game_id: string
          id?: string
          name: string
          opponent_player_id?: string | null
        }
        Update: {
          created_at?: string
          game_id?: string
          id?: string
          name?: string
          opponent_player_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "game_opponent_pitchers_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_opponent_pitchers_opponent_player_id_fkey"
            columns: ["opponent_player_id"]
            isOneToOne: false
            referencedRelation: "opponent_players"
            referencedColumns: ["id"]
          },
        ]
      }
      games: {
        Row: {
          created_at: string
          finalized_at: string | null
          game_date: string
          game_sequence: number
          game_time: string | null
          id: string
          is_final: boolean
          is_home: boolean
          location: string
          notes: string | null
          opponent: string
          opponent_score: number | null
          opponent_team_id: string | null
          result: string | null
          result_type: string
          season_year: number | null
          status: string
          team_id: string
          team_score: number | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          finalized_at?: string | null
          game_date: string
          game_sequence?: number
          game_time?: string | null
          id?: string
          is_final?: boolean
          is_home: boolean
          location?: string
          notes?: string | null
          opponent: string
          opponent_score?: number | null
          opponent_team_id?: string | null
          result?: string | null
          result_type?: string
          season_year?: number | null
          status?: string
          team_id: string
          team_score?: number | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          finalized_at?: string | null
          game_date?: string
          game_sequence?: number
          game_time?: string | null
          id?: string
          is_final?: boolean
          is_home?: boolean
          location?: string
          notes?: string | null
          opponent?: string
          opponent_score?: number | null
          opponent_team_id?: string | null
          result?: string | null
          result_type?: string
          season_year?: number | null
          status?: string
          team_id?: string
          team_score?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "games_opponent_team_id_fkey"
            columns: ["opponent_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "games_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      opponent_players: {
        Row: {
          bats: string | null
          created_at: string
          external_player_id: string | null
          first_name: string | null
          grad_year: number | null
          id: string
          jersey_number: string | null
          last_name: string | null
          opponent_team_id: string | null
          school_id: string
          throws: string | null
          updated_at: string
        }
        Insert: {
          bats?: string | null
          created_at?: string
          external_player_id?: string | null
          first_name?: string | null
          grad_year?: number | null
          id?: string
          jersey_number?: string | null
          last_name?: string | null
          opponent_team_id?: string | null
          school_id: string
          throws?: string | null
          updated_at?: string
        }
        Update: {
          bats?: string | null
          created_at?: string
          external_player_id?: string | null
          first_name?: string | null
          grad_year?: number | null
          id?: string
          jersey_number?: string | null
          last_name?: string | null
          opponent_team_id?: string | null
          school_id?: string
          throws?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "opponent_players_external_player_id_fkey"
            columns: ["external_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opponent_players_opponent_team_id_fkey"
            columns: ["opponent_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opponent_players_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      players: {
        Row: {
          created_at: string
          first_name: string
          grad_year: number | null
          id: string
          last_name: string
          school_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          first_name: string
          grad_year?: number | null
          id?: string
          last_name: string
          school_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          first_name?: string
          grad_year?: number | null
          id?: string
          last_name?: string
          school_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "players_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      roster_entries: {
        Row: {
          created_at: string
          id: string
          jersey_number: string | null
          player_id: string
          position: string | null
          season_year: number
          team_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          jersey_number?: string | null
          player_id: string
          position?: string | null
          season_year: number
          team_id: string
        }
        Update: {
          created_at?: string
          id?: string
          jersey_number?: string | null
          player_id?: string
          position?: string | null
          season_year?: number
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "roster_entries_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roster_entries_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      school_admins: {
        Row: {
          allow_coach_contact: boolean
          created_at: string
          role: string
          school_id: string
          user_id: string
        }
        Insert: {
          allow_coach_contact?: boolean
          created_at?: string
          role?: string
          school_id: string
          user_id: string
        }
        Update: {
          allow_coach_contact?: boolean
          created_at?: string
          role?: string
          school_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "school_admins_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      schools: {
        Row: {
          association: string | null
          classification: string | null
          created_at: string
          division: string | null
          id: string
          is_discoverable: boolean
          is_public_roster: boolean
          logo_url: string | null
          name: string
          primary_color: string | null
          public_scores_enabled: boolean
          region: string | null
          secondary_color: string | null
          short_name: string | null
          slug: string
          timezone: string
          updated_at: string
        }
        Insert: {
          association?: string | null
          classification?: string | null
          created_at?: string
          division?: string | null
          id?: string
          is_discoverable?: boolean
          is_public_roster?: boolean
          logo_url?: string | null
          name: string
          primary_color?: string | null
          public_scores_enabled?: boolean
          region?: string | null
          secondary_color?: string | null
          short_name?: string | null
          slug: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          association?: string | null
          classification?: string | null
          created_at?: string
          division?: string | null
          id?: string
          is_discoverable?: boolean
          is_public_roster?: boolean
          logo_url?: string | null
          name?: string
          primary_color?: string | null
          public_scores_enabled?: boolean
          region?: string | null
          secondary_color?: string | null
          short_name?: string | null
          slug?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      score_discrepancies: {
        Row: {
          game_link_id: string
          home_acct_home_score: number | null
          home_acct_visitor_score: number | null
          home_self_confirmed: boolean
          id: string
          opened_at: string
          resolved_at: string | null
          vis_acct_home_score: number | null
          vis_acct_visitor_score: number | null
          visitor_self_confirmed: boolean
        }
        Insert: {
          game_link_id: string
          home_acct_home_score?: number | null
          home_acct_visitor_score?: number | null
          home_self_confirmed?: boolean
          id?: string
          opened_at?: string
          resolved_at?: string | null
          vis_acct_home_score?: number | null
          vis_acct_visitor_score?: number | null
          visitor_self_confirmed?: boolean
        }
        Update: {
          game_link_id?: string
          home_acct_home_score?: number | null
          home_acct_visitor_score?: number | null
          home_self_confirmed?: boolean
          id?: string
          opened_at?: string
          resolved_at?: string | null
          vis_acct_home_score?: number | null
          vis_acct_visitor_score?: number | null
          visitor_self_confirmed?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "score_discrepancies_game_link_id_fkey"
            columns: ["game_link_id"]
            isOneToOne: false
            referencedRelation: "game_links"
            referencedColumns: ["id"]
          },
        ]
      }
      stat_snapshots: {
        Row: {
          created_at: string
          game_id: string | null
          id: string
          player_id: string
          season_year: number | null
          source: string
          stats: Json
          team_id: string
          upload_date: string
          upload_id: string | null
        }
        Insert: {
          created_at?: string
          game_id?: string | null
          id?: string
          player_id: string
          season_year?: number | null
          source?: string
          stats: Json
          team_id: string
          upload_date: string
          upload_id?: string | null
        }
        Update: {
          created_at?: string
          game_id?: string | null
          id?: string
          player_id?: string
          season_year?: number | null
          source?: string
          stats?: Json
          team_id?: string
          upload_date?: string
          upload_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "stat_snapshots_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stat_snapshots_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stat_snapshots_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stat_snapshots_upload_id_fkey"
            columns: ["upload_id"]
            isOneToOne: false
            referencedRelation: "csv_uploads"
            referencedColumns: ["id"]
          },
        ]
      }
      team_members: {
        Row: {
          created_at: string
          role: string
          team_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          role?: string
          team_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          role?: string
          team_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_members_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          created_at: string
          id: string
          league_type: string
          level: string
          name: string
          nfhs_state: string | null
          pitch_limits: Json | null
          school_id: string
          slug: string
          sport: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          league_type?: string
          level: string
          name: string
          nfhs_state?: string | null
          pitch_limits?: Json | null
          school_id: string
          slug: string
          sport: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          league_type?: string
          level?: string
          name?: string
          nfhs_state?: string | null
          pitch_limits?: Json | null
          school_id?: string
          slug?: string
          sport?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "teams_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _score_discrepancy_recompute_for_link: {
        Args: { p_link_id: string; p_score_changed_side: string }
        Returns: undefined
      }
      apply_relink: {
        Args: { p_game_ids: string[]; p_target_team_id: string }
        Returns: number
      }
      confirm_game_link: {
        Args: { p_home_game_id: string; p_visitor_game_id: string }
        Returns: string
      }
      confirm_my_score: { Args: { p_link_id: string }; Returns: undefined }
      create_school: {
        Args: { p_name: string; p_slug: string }
        Returns: {
          association: string | null
          classification: string | null
          created_at: string
          division: string | null
          id: string
          is_discoverable: boolean
          is_public_roster: boolean
          logo_url: string | null
          name: string
          primary_color: string | null
          public_scores_enabled: boolean
          region: string | null
          secondary_color: string | null
          short_name: string | null
          slug: string
          timezone: string
          updated_at: string
        }
        SetofOptions: {
          from: "*"
          to: "schools"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      find_relink_suggestions: {
        Args: { p_team_id: string }
        Returns: {
          candidate_school_id: string
          candidate_school_name: string
          candidate_school_short_name: string
          candidate_team_id: string
          candidate_team_level: string
          candidate_team_name: string
          game_date: string
          game_id: string
          game_time: string
          opponent_text: string
        }[]
      }
      game_match_candidates: {
        Args: { p_my_game_id: string }
        Returns: {
          candidate_game_id: string
          game_date: string
          game_sequence: number
          game_time: string
          is_home: boolean
          status: string
        }[]
      }
      get_public_roster: {
        Args: { p_season_year: number; p_team_id: string }
        Returns: {
          external_player_id: string
          first_name: string
          grad_year: number
          jersey_number: string
          last_name: string
          position: string
        }[]
      }
      ingest_schedule: {
        Args: {
          p_games: Json
          p_on_conflict: string
          p_school: string
          p_team: string
        }
        Returns: {
          conflict_dates: string[]
          inserted: number
          skipped: number
          updated: number
        }[]
      }
      ingest_stats_workbook: {
        Args: {
          p_filename: string
          p_players: Json
          p_replace: boolean
          p_school: string
          p_team: string
          p_upload_date: string
        }
        Returns: {
          snapshot_count: number
          upload_id: string
        }[]
      }
      is_school_admin: { Args: { p_school: string }; Returns: boolean }
      is_season_closed: { Args: { yr: number }; Returns: boolean }
      is_team_member: { Args: { p_team: string }; Returns: boolean }
      recognize_opponent_team: {
        Args: { p_my_team_id: string; p_opponent_text: string }
        Returns: {
          school_id: string
          school_name: string
          short_name: string
          team_id: string
        }[]
      }
      season_year_for: { Args: { d: string }; Returns: number }
      unlink_games: { Args: { p_link_id: string }; Returns: undefined }
      upsert_opponent_players: {
        Args: { p_rows: Json; p_school: string }
        Returns: {
          client_ref: string
          opponent_player_id: string
        }[]
      }
      upsert_roster: {
        Args: {
          p_has_grad_year: boolean
          p_has_number: boolean
          p_has_position: boolean
          p_players: Json
          p_school: string
          p_season: number
          p_team: string
        }
        Returns: {
          first_name: string
          last_name: string
          player_id: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
